name: Build phar

on:
  workflow_dispatch:
  push:
    branches:
      - pm5

jobs:
  pharynx:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer

      - run: composer install --ignore-platform-reqs

      - uses: SOF3/pharynx@v0.2
        id: pharynx
        with:
          additional-assets: |
            icon.png

      - uses: actions/upload-artifact@v4
        with:
          name: BedrockEconomy.phar
          path: ${{ steps.pharynx.outputs.output-phar }}
